### PR TITLE
feat: docker

### PR DESCRIPTION
**Pull request by Chicken**
add docker stuff

### CODE REVIEW

**Comment by StrangeGirlMurph** [comment]
well I have pretty much no idea how docker works but I trust you :)
Just to make sure is the docker image suited to work on a raspberry pi?

**Comment by Chicken** [comment]
yes.

**Comment by Chicken** [comment]
or atleast a arm64 one

**Review by StrangeGirlMurph — APPROVED** [review]

**Review by BlackDemonFire — APPROVED** [review]
looks good

**Pull request merged**
